#!/usr/bin/env python3
"""
make_python_majority.py

Makes Python the majority language on a GitHub repo by generating
a .gitattributes file that excludes non-Python files from Linguist's
language statistics.

Usage:
    python make_python_majority.py /path/to/repo [--mode exclude|reclassify] [--dry-run]

Modes:
    exclude     - Mark all non-Python files as linguist-vendored (excluded from stats)
    reclassify  - Force non-Python files to be counted as Python (linguist-language=Python)

Strategy: By default, uses "exclude" mode which is the safest — it removes
non-Python files from the language bar entirely, leaving Python as 100%.
Use "reclassify" mode only if you also want them counted as Python bytes.
"""

import os
import sys
import argparse
from pathlib import Path

# Files/dirs that should never be touched
IGNORE_DIRS = {
    ".git", ".github", "node_modules", "__pycache__", ".venv", "venv",
    "env", ".env", ".idea", ".vscode", ".mypy_cache", ".pytest_cache",
    ".tox", ".eggs", "dist", "build", "*.egg-info",
}

PYTHON_EXTENSIONS = {".py", ".pyw", ".pyx"}

# Common non-Python extensions you might want to keep detectable
# (add or remove as needed)
KEEP_DETECTABLE = set()  # e.g. {".sql"} to let SQL show in stats


def should_ignore(path: Path) -> bool:
    parts = path.parts
    for ignored in IGNORE_DIRS:
        if any(ignored in part for part in parts):
            return True
    return False


def is_python_file(path: Path) -> bool:
    return path.suffix in PYTHON_EXTENSIONS


def find_non_python_files(root: Path) -> list[Path]:
    """Find all non-binary, non-Python files in the repo."""
    non_py_files = []
    for dirpath, dirnames, filenames in os.walk(root):
        # Prune ignored dirs in-place
        dirnames[:] = [d for d in dirnames if d not in IGNORE_DIRS]
        for fname in filenames:
            fpath = Path(dirpath) / fname
            if should_ignore(fpath):
                continue
            if fname == ".gitattributes":
                continue
            if is_python_file(fpath):
                continue
            if fpath.suffix in KEEP_DETECTABLE:
                continue
            # Skip binary files (rough heuristic)
            try:
                fpath.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            # Get path relative to root
            rel = fpath.relative_to(root)
            non_py_files.append(rel)
    return sorted(non_py_files)


def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Make Python the majority language on a GitHub repo."
    )
    parser.add_argument("repo_path", help="Path to the Git repository root")
    parser.add_argument(
        "--mode",
        choices=["exclude", "reclassify"],
        default="exclude",
        help="exclude (default): removes non-Python from stats; reclassify: counts them as Python",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing file")
    args = parser.parse_args()

    root = Path(args.repo_path).resolve()
    if not (root / ".git").exists():
        print(f"Warning: {root} does not appear to be a Git repository.", file=sys.stderr)

    non_py = find_non_python_files(root)
    if not non_py:
        print("No non-Python files found. Python is already the only language.")
        return

    print(f"Found {len(non_py)} non-Python file(s). Mode: {args.mode}")
    content = build_gitattributes(non_py, args.mode)

    if args.dry_run:
        print("--- .gitattributes ---")
        print(content)
    else:
        outpath = root / ".gitattributes"
        existing = ""
        if outpath.exists():
            existing = outpath.read_text()
            # Back up existing file
            backup = root / ".gitattributes.bak"
            backup.write_text(existing)
            print(f"Backed up existing .gitattributes to {backup.name}")

        outpath.write_text(content)
        print(f"Wrote {outpath}")
        print("Commit and push to see updated language stats on GitHub.")
        print("Note: GitHub may take a few minutes to recalculate.")
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)
def build_gitattributes(non_py_files: list[Path], mode: str) -> str:
    lines = [
        "# Auto-generated by make_python_majority.py",
        "# Makes Python the majority language on GitHub by adjusting Linguist stats.",
        "",
    ]
    if mode == "exclude":
        lines.append("# Exclude non-Python files from language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-vendored")
    elif mode == "reclassify":
        lines.append("# Reclassify non-Python files as Python for language statistics")
        for f in non_py_files:
            lines.append(f"{f} linguist-language=Python")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
